server:
  extraArgs:
    - --auth-mode=server ## The argo-server (and thus the UI) defaults to client authentication, which requires clients to provide their Kubernetes bearer token in order to authenticate, We switch the authentication mode to server so that we can bypass the UI login
  # serviceType: NodePort  ## use NodePort instead of ingress if you want
  # serviceNodePort: 32746
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - devops.hobbies
