apiVersion: networking.k8s.io/v1  # এটি Kubernetes-এর Ingress API ব্যবহার করছে
kind: Ingress   #  এটি একটি Ingress Resource, যা HTTP এবং HTTPS ট্র্যাফিক রাউট করার জন্য ব্যবহৃত হয়।
metadata:
  name: nginx-ingress  # এটি Ingress Resource-এর নাম।
spec:
  ingressClassName: nginx   # Ingress Controller হিসেবে nginx ব্যবহার করা হচ্ছে
  rules:  #ক্লাস্টারে nginx-ingress-controller চালু thakte hobe,kubectl get pods -n ingress-nginx #
  - host: argo.demo  # ডোমেইন argo.demo-তে যখন কোনো রিকোয়েস্ট আসবে, তখন এটি নির্দিষ্ট সার্ভিসে পাঠাবে।
    http:       # ডোমেইন রেজিস্টার করা না থাকলে /etc/hosts ফাইল আপডেট করুন
      paths:
      - backend:
          service:      # এই Ingress Resource rollout-bluegreen-active সার্ভিসে HTTP ট্র্যাফিক পাঠাবে।
            name: nginx-service
            port:
              number: 8080
        path: /       # Root path /-এ আসা সব HTTP রিকোয়েস্ট Ingress-এর মাধ্যমে সার্ভিসে যাবে।
        pathType: Prefix
