apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-generator-ex1
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        path: directoryOfmanifests
      - cluster: external
        url: https://192.168.64.93:6443
        path: helm/nginx
  template:
    metadata:
      name: '{{cluster}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/devopshobbies/argocd-tutorial.git
        targetRevision: main
        path: v03-argocd-applications/{{path}}
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true