apiVersion: batch/v1                    #এই YAML-টি Kubernetes-এর batch/v1 API Group ব্যবহার করছ যেটা Job resource তৈরি করতে ব্যবহৃত হয়।
kind: Job                                       #এটা একটি Job। অর্থাৎ একবার রান করে শেষ হবে এমন কাজ (one-time task), যেটা ব্যাকগ্রাউন্ডে শেষ
metadata:
  name: mattermost-post-job-failure     #এই Job-এর নাম mattermost-post-job-failure  তুমি Mattermost-এ কোনো Sync failure ঘটলে বার্তা পাঠাতে এই Job তৈরি করছো।
  annotations:
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
        - name: mattermost-failure              #এখানে একটি কনটেইনার তৈরি হচ্ছে যার নাম mattermost-failure
          image: 172.17.0.233:5000/mattermost:final              #এটি mattermost:final নামের Docker image ব্যবহার করছে।
          command: [ "python3", "mattermost_api.py"]    #কনটেইনার চালু হলে Python দিয়ে mattermost_api.py স্ক্রিপ্ট রান করাবে
          env:
          - name: message                       #তুমি কী বার্তা পাঠাবে Matterm এখানে Sync Failed বার্তা আছে
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync Failed ***"
          - name: url
            value: "172.17.0.232"               #Mattermost server-এর IP address
          - name: token
            value: "q946romn4pruxbzzk59uje4wua"     #Mattermost bot/token — তুমি Mattermost UI থেকে generate করে দিবে।
          - name: scheme
            value: "http"                                       #HTTP প্রোটোকল ব্যবহার করবে
          - name: port
            value: "8065"                                       #Mattermost এর ডিফল্ট পোর্ট
          - name: channel_name
            value: "argocd-alert"                                     #যে চ্যানেলে মেসে argocd নামে।
          - name: team_name
            value: "digicon"                            #Mattermost-এ যেই টিমে মেসেজ সেটি হলো digicon
      restartPolicy: Never                                      #এই Job একবার চলবে, fail করলেও পুনরায় চালাবে না।
  backoffLimit: 0
