apiVersion: batch/v1			#এই YAML-টি Kubernetes-এর batch/v1 API Group ব্যবহার করছে — যেটা Job resource তৈরি করতে ব্যবহৃত হয়।
kind: Job					#এটা একটি Job। অর্থাৎ একবার রান করে শেষ হবে এমন কাজ (one-time task), যেটা ব্যাকগ্রাউন্ডে শেষ হবার জন্য চালানো হয়।
metadata:
  name: mattermost-post-job-success	#st-post-job-failure — তুমি Mattermost-এ কোনো Sync failure ঘটলে বার্তা পাঠাতে এই Job তৈরি করছো।
  annotations:
    argocd.argoproj.io/hook: Postsync
  template:
    spec:
      containers:
        - name: mattermost-success		#এখানে একটি কনটেইনার তৈরি হচ্ছে যার নাম mattermost-failure
          image: mattermost:final		#এটি mattermost:final নামের Docker image ব্যবহার করছে।
          command: [ "python3", "mattermost_api.py"]	#কনটেইনার চালু হলে Python দিয়ে mattermost_api.py স্ক্রিপ্ট রান করাবে
          env:
          - name: message			#তুমি কী বার্তা পাঠাবে Mattermost-এ — এখানে Sync Failed বার্তা আছে
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync OK ***"
          - name: url
            value: "172.17.0.224"		#Mattermost server-এর IP address
          - name: token-for-digicon
            value: "jhyd9rroqjf65cfohh3yhp8par"     #Mattermost bot/token — তুমি Mattermost UI থেকে generate করে দিবে।
          - name: scheme
            value: "http"					#HTTP প্রোটোকল ব্যবহার করবে
          - name: port
            value: "8065"					#Mattermost এর ডিফল্ট পোর্ট
          - name: channel_name
            value: "devops"     				#যে চ্যানেলে মেসেজ যাবে — argocd নামে।
          - name: team_name
            value: "digicon"        			#Mattermost-এ যেই টিমে মেসেজ যাবে — সেটি হলো digicon
      restartPolicy: Never					#এই Job একবার চলবে, fail করলেও পুনরায় চালাবে না।
  backoffLimit: 0							#0 মানে, ব্যর্থ হলে পুনরায় চালানোর কোনো চেষ্টাই করবে না।
