apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-demo-
spec:
  arguments:
    parameters:
      - name: repo-url
        value: "https://github.com/nuruzzaman24x/argocd-tutorial.git"
      - name: branch
        value: main
      - name: docker-hosted
        value: 172.17.0.233:5000
  artifactRepositoryRef:
    configMap: artifact-repository
  entrypoint: ci
  templates:
  - name: ci
    dag:
      tasks:
        - name: clone-repo-task
          templateRef:
            name: clone-repo-wf-template
            template: clone-repo
          arguments:
            parameters:
              - name: repo-url
                value: "{{workflow.parameters.repo-url}}"
              - name: branch
                value: "{{workflow.parameters.branch}}"

        - name: build-push-task
          templateRef:
            name: build-push-wf-template
            template: build-and-push
          arguments:
            artifacts:
              - name: source
                from: "{{tasks.clone-repo-task.outputs.artifacts.source}}"
          dependencies: [clone-repo-task]

        - name: update-manifest-task
          templateRef:
            name: update-manifest-wf-template
            template: update-manifest
          arguments:
            artifacts:
              - name: source
                from: "{{tasks.clone-repo-task.outputs.artifacts.source}}"
          dependencies: [clone-repo-task, build-push-task]
