apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-generator-ex1
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/devopshobbies/argocd-tutorial.git
              revision: main
              directories:
                - path: v09-argocd-applicationSet-1/git-generator/resources/*
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/devopshobbies/argocd-tutorial.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{metadata.labels.environment}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true